apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'kotlin-kapt'

apply plugin: "androidx.navigation.safeargs"

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.combah.travel2"
        minSdkVersion 15
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.0.0'

    // Lifecycle
    implementation 'android.arch.lifecycle:extensions:1.1.1'
    implementation 'android.arch.lifecycle:reactivestreams:1.1.1'
    kapt 'android.arch.lifecycle:compiler:1.1.1'

    // Navigation
    implementation "android.arch.navigation:navigation-fragment-ktx:1.0.0-alpha06" // use -ktx for Kotlin
    implementation "android.arch.navigation:navigation-ui-ktx:1.0.0-alpha06" // use -ktx for Kotlin

    // Litho
    implementation 'com.facebook.litho:litho-core:0.19.0'
    implementation 'com.facebook.litho:litho-widget:0.19.0'
    compileOnly 'com.facebook.litho:litho-annotations:0.19.0'
    kapt 'com.facebook.litho:litho-processor:0.19.0'

    // SoLoader
    implementation 'com.facebook.soloader:soloader:0.5.1'

    // For integration with Fresco
    implementation 'com.facebook.litho:litho-fresco:0.19.0'

    // Sections
    implementation 'com.facebook.litho:litho-sections-core:0.19.0'
    implementation 'com.facebook.litho:litho-sections-widget:0.19.0'
    compileOnly 'com.facebook.litho:litho-sections-annotations:0.19.0'

    kapt 'com.facebook.litho:litho-sections-processor:0.19.0'

    // Dagger
    implementation 'com.google.dagger:dagger:2.16'
    implementation 'com.google.dagger:dagger-android-support:2.16'
    kapt 'com.google.dagger:dagger-compiler:2.16'
    kapt 'com.google.dagger:dagger-android-processor:2.16'
    compileOnly 'org.glassfish:javax.annotation:10.0-b28'

    // Firebase
    implementation 'com.google.android.gms:play-services-auth:16.0.0'
    implementation 'com.google.firebase:firebase-core:16.0.3'
    implementation 'com.google.firebase:firebase-firestore:17.1.0'

    // Rx
    implementation 'io.reactivex.rxjava2:rxjava:2.2.0'
    implementation 'io.reactivex.rxjava2:rxandroid:2.0.2'
    implementation 'io.reactivex.rxjava2:rxkotlin:2.3.0'

    testImplementation 'junit:junit:4.12'
    testImplementation 'org.mockito:mockito-core:2.21.0'
    testImplementation 'com.nhaarman:mockito-kotlin:1.5.0'
    testImplementation 'android.arch.core:core-testing:1.1.1'
    androidTestImplementation 'androidx.test:runner:1.1.0-alpha4'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha4'


    testImplementation 'com.facebook.litho:litho-testing:0.18.0'
}

apply plugin: 'com.google.gms.google-services'
